### ISSUE TITLE
Gear indication via trail color

### ISSUE THREAD

**Issue by VellVee** [codecat/tm-editor-trails#5]
Great job with the plugin so far! One feature that i would like to see is to add an option to have trails change color depending on the current gear. Another way would be to put a point on the line that would indicate where exacly gear change happened. That would be very helpful for people like me, who still sometimes struggle with gear calculation on maps.

**Comment by codecat** [comment]
That's a really good idea! Maybe just showing a little bubble with a number too.

**Comment by codecat** [comment]
Something like this, maybe!

![image](https://user-images.githubusercontent.com/136534/213926342-2b8a0445-d773-456c-b1a4-075c034a93fc.png)
